name: neuro-stackedtimeseries
channels:
  - conda-forge
dependencies:
  - python
  - holoviews>=1.18
  - bokeh>=3.3
  - hvplot
  - panel
#  - datashader
  - numpy
  - pandas
  - xarray
  - ipykernel
  - mne
#  - neurodsp
  - jupyterlab
  - intake
  - zarr
  - kerchunk
  - pip
  - pip:
 #   - -e ../../src/neurodatagen
 #   - -e ../../src/hvneuro
